### ISSUE TITLE
Parsing Error in different WFS Services

### ISSUE THREAD

**Issue by jsaalfeld** [Intevation/downloadclient#14]
While trying to parse some WFS 2.0 Services we experienced an issue with most of the services. While initializing the [WFS 2 Object](/Intevation/downloadclient/blob/master/src/main/java/de/bayern/gdi/services/WFSTwo.java), we fetch the data from the service and try to parse them. But while parsing then an excpetion rises:

`Parsing failed for FeatureType: java.lang.RuntimeException: Unable to set property: OutputFormats for eobject: {http://www.opengis.net/wfs/2.0}FeatureTypeType
java.lang.RuntimeException: Parsing failed for FeatureType: java.lang.RuntimeException: Unable to set property: OutputFormats for eobject: {http://www.opengis.net/wfs/2.0}FeatureTypeType
    at org.geotools.xml.impl.ParseExecutor.visit(ParseExecutor.java:165)
    at org.geotools.xml.impl.BindingWalker$BindingExecutionChain.execute(BindingWalker.java:220)
    at org.geotools.xml.impl.BindingWalker.walk(BindingWalker.java:186)
    at org.geotools.xml.impl.ElementHandlerImpl.endElement(ElementHandlerImpl.java:236)
    at org.geotools.xml.impl.ParserHandler.endElement(ParserHandler.java:744)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1783)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2970)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
    at org.geotools.xml.Parser.parse(Parser.java:249)
    at de.bayern.gdi.services.WFSTwo.<init>(WFSTwo.java:100)
    at de.bayern.gdi.gui.Controller$ServiceChooseButtonEventHandler$1.call(Controller.java:338)
    at de.bayern.gdi.gui.Controller$ServiceChooseButtonEventHandler$1.call(Controller.java:254)
    at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to set property: OutputFormats for eobject: {http://www.opengis.net/wfs/2.0}FeatureTypeType
    at org.geotools.xml.AbstractComplexEMFBinding.setProperty(AbstractComplexEMFBinding.java:301)
    at org.geotools.wfs.v2_0.bindings.FeatureTypeTypeBinding.setProperty(FeatureTypeTypeBinding.java:114)
    at org.geotools.xml.AbstractComplexEMFBinding.setProperties(AbstractComplexEMFBinding.java:206)
    at org.geotools.xml.AbstractComplexEMFBinding.parse(AbstractComplexEMFBinding.java:147)
    at org.geotools.xml.impl.ParseExecutor.visit(ParseExecutor.java:156)
    ... 23 more
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to net.opengis.wfs20.OutputFormatListType
    at net.opengis.wfs20.impl.FeatureTypeTypeImpl.eSet(FeatureTypeTypeImpl.java:553)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1081)
    at org.geotools.xml.EMFUtils.set(EMFUtils.java:69)
    at org.geotools.xml.AbstractComplexEMFBinding.setProperty(AbstractComplexEMFBinding.java:236)
    ... 27 more`

To our knowledge this means either that the parser is too strict or the called service is not correctly implemented.

This seems to be a known issue, since there is an open Bug since last year: https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5125?filter=allopenissues

**Comment by jsaalfeld** [comment]
The main difference in services we could test until now, is that the services that work with the framework only list one value: at the "outputFormat". It seems, there is an error, when the return of the outputFormat is longer than 1.

**Comment by dmth** [comment]
@jsaalfeld does this bug still exist?

**Comment by s-l-teichmann** [comment]
We are not using any GeoTools WFS stuff any more, so this concrete issue is obsolete.
