### ISSUE TITLE
Using DownloadSchritt-WFS2_*.xml in headless mode causes Null-Pointer Exception

### ISSUE THREAD

**Issue by dmth** [Intevation/downloadclient#42]
A Null-Pointer exception is raised when trying to download from WFS 2.0 basic and simple and using the provided example download-step files.

```
INFORMATION: Using download config file: DownloadSchritt-WFS2_Basic.xml
Mai 31, 2016 9:18:19 AM de.bayern.gdi.Headless main
INFORMATION: Download configuration: [DownloadStep:
        serviceType: "WFS2_BASIC"
        serviceURL: "http://geoserv.weichand.de:8080/geoserver/wfs"
        dataset: "bvv:gmd_ex"
        path: "/tmp/"
        parameters: [Parameter: key = "srsName" value = "urn:ogc:def:crs:EPSG::31468"], [Parameter: key = "bbox" value = "5500000,4500000,5500500,4500500,urn:ogc:def:crs:EPSG::31468"]]
        processing steps:
]
Mai 31, 2016 9:18:19 AM de.bayern.gdi.processor.DownloadStepConverter createWfsDownload
INFORMATION: url: http://geoserv.weichand.de:8080/geoserver/wfs?service=wfs&request=GetFeature&version=2.0.0&typeNames=bvv%3Agmd_ex&srsName=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A31468&bbox=5500000%2C4500000%2C5500500%2C4500500%2Curn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A31468
Mai 31, 2016 9:18:19 AM de.bayern.gdi.processor.DownloadStepConverter createWfsDownload
INFORMATION: Download to file "/tmp/gdibydl-20160531091819/download.gml"
Mai 31, 2016 9:18:19 AM de.bayern.gdi.processor.JobList run
INFORMATION: Executing job list
[WARNING] 
java.lang.NullPointerException
        at de.bayern.gdi.processor.FileDownloadJob.download(FileDownloadJob.java:74)
        at de.bayern.gdi.processor.AbstractDownloadJob.run(AbstractDownloadJob.java:62)
        at de.bayern.gdi.processor.JobList.run(JobList.java:52)
        at de.bayern.gdi.processor.Processor.run(Processor.java:149)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dmth** [comment]
L74 is `this.processor.broadcastMessage(I18n.getMsg("file.download.start"));`
