### ISSUE TITLE
Downloadclient does not start when build from jar

### ISSUE THREAD

**Issue by dmth** [Intevation/downloadclient#94]
If I create a jar from the latest merge of "master" and "return_distinct_info_about_service" branch, the resulting application cannot be started on windows:

```
E:\>java -jar downloadclient-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierar
chical
        at java.io.File.<init>(Unknown Source)
        at de.bayern.gdi.model.ProcessingConfiguration.loadDefault(ProcessingCon
figuration.java:181)
        at de.bayern.gdi.utils.Config.uninitialized(Config.java:114)
        at de.bayern.gdi.App.main(App.java:128)
```

**Comment by dmth** [comment]
It happens when the JAR is build...

```
java -jar downloadclient-1.0-SNAPSHOT.jar 
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418)
        at de.bayern.gdi.model.ProcessingConfiguration.loadDefault(ProcessingConfiguration.java:181)
        at de.bayern.gdi.utils.Config.uninitialized(Config.java:114)
        at de.bayern.gdi.App.main(App.java:128)
```

**Comment by dmth** [comment]
Fixed now.
